# This file isn't intended for editing unless you know exactly what you're doing.

#############################################################################################

remote_theme: just-the-docs/just-the-docs

title: "Yi Xian Wiki"
description: ""

url: https://YiXianCardGame.github.io
baseurl: "" # what?

search_enabled: true # adds search bar at the top of the page
heading_anchors: true # the thing where you can hover over the heading and lets you copy the link

# light = death
color_scheme: dark

# NOTE: Add favicon later
favicon_ico: "/assets/images/favicon.ico"

#############################################################################################

callouts:
  warning:
    color: red
  highlight:
    color: yellow
  new:
    color: green
  important:
    color: blue
  note:
    color: purple
  HELLO:
    title: Hello Message
    color: green

#############################################################################################